version: '2'
services:
  sam-scheduledsending-db:
    image: "couchdb:1.6.1"
    hostname: couchdb.server
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: admin
    ports:
      - "5984:5984"
  sam-scheduledsending-ms:
    #build: .
    image: akosoriod/scheduledsending
    command: node app
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3006:3006"
    depends_on:
      - sam-scheduledsending-db
